[package]
name = "transform-output"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
strum = "0.15"
strum_macros = "0.15"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
